apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: treasurehunt
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests
    repoURL: https://github.com/saurabh-saha/treasureHunt-suse
    targetRevision: HEAD
  syncPolicy: {}
