apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: treasurehunt
  name: python-helloworld
  namespace: default 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: treasurehunt
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: treasurehunt
    spec:
      containers:
      - image: saurabhsaha91/treasure-hunt:v2.0
        imagePullPolicy: IfNotPresent
        name: treasurehunt
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
